spring.application.name=venues
spring.profiles.active=dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db.duarcqclarkrwsuphec.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Kb334miRvcMcINcK
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=always
server.error.include-binding-errors=never

