spring.application.name=venues
spring.profiles.active=dev
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=always
server.error.include-binding-errors=never
